### ISSUE TITLE
Can't see ignore pain

### ISSUE THREAD

**Issue by tomithus** [sunaurus/ElvUI_TankHealth#4]
I've tried all kinds of options and i downloaded the tank heals plug in but i just cannot get ignore pain to show up on my payer unit frame. google is too saturated for me to find any help there : /

**Comment by sunaurus** [comment]
What version of ElvUI are you on? 

Can you type the command '/th debug' into chat to open a debug window, then do some damage on a tanking dummy and post a screenshot of the result?

**Comment by zigzaggin** [comment]
It looks like it isn't unique to IP, Frenzied Regen on my druid only displays over healing when it extends past the bar. 
![image](https://cloud.githubusercontent.com/assets/5532807/19542737/12930756-962e-11e6-87bb-9bc9d230e7f2.png)

**Comment by tomithus** [comment]
Here it calculates the rage i have into what looks like what my ignore pain would be if i used the ability

![wowscrnshot_102016_211241](https://cloud.githubusercontent.com/assets/22925681/19586505/4c3de476-970a-11e6-9125-ebeefd9331b0.jpg)

Here after i use ignore pain there is no display of the absorb.

![wowscrnshot_102016_211244](https://cloud.githubusercontent.com/assets/22925681/19586540/ac542596-970a-11e6-9604-5d9ec2179687.jpg)

I'm using version 10.23

edit: 

I guess i totally missed it but it works if I'm missing hp. But if I am topped off, there are no visuals. This would still present a problem to me as i would build ignore pain up being topped off as an off tank for a taunting scenario.
![wowscrnshot_102016_212313](https://cloud.githubusercontent.com/assets/22925681/19586615/bbd60a7e-970b-11e6-8152-9f9ad3712841.jpg)

**Comment by sunaurus** [comment]
@zigzaggin , it looks like you were using a newer version of ElvUI, which changed the way healthbars work. Your issue SHOULD be fixed in TankHealth 1.11, but let me know if it's not.

@tomithus , try to open your ElvUI settings (type /ec into chat), select TankHealth from the left side menu, and enable the checkbox "Show overheal", let me know if that does what you want.

**Comment by sunaurus** [comment]
@tomithus also, if you want to see the size of the absorb AFTER you've used it, then that should be configured somewhere in ElvUI settings (should be a setting to extend absorbs past health bar or something). The option I mentioned in TankHealth settings will only extend the absorb prediction BEFORE using it past the health bar, showing the absorb itself is handled by ElvUI.
